#
# Jekyll basic configurations
#

# Expose site to local network
host:           0.0.0.0

# Re-include theme example pages for development
exclude:        []

plugins:
  - jekyll-last-modified-at
  - jekyll-paginate

#
# Almace Scaffolding settings
#

# Enable development mode
dev:            true

# Reset base to / for localhost development
baseurl:        ""

# CDN location for development
file:           //

# Force UTF-8 since local server doesn't send charset in their respond header
force_utf_8:    true
